### ISSUE TITLE
SSH or tmate access to running container

### ISSUE THREAD

**Issue by zupo** [teamniteo/nix-docker-base#9]
Sometimes I need SSH access to a running container to debug certain issues. For example CI problems on CircleCI or on GitHub Actions. For latter, there is https://github.com/marketplace/actions/debugging-with-tmate, but that depends on having a bunch of ubuntu things available. Can we do something similar?

**Comment by zupo** [comment]
CircleCI's "Rerun Job with SSH" also seems like it does not work. The job starts and prints out the IP to connect to, but when I try to connect I get `connection refused`.

**Comment by infinisil** [comment]
@zupo Regarding CircleCI's "Rerun Job with SSH", that seems to work in my testing. See https://github.com/Infinisil/github-actions-docker for the CircleCI config I used.

**Comment by zupo** [comment]
@Infinisil: oh wow, OK, lemme re-test it!

**Comment by infinisil** [comment]
I also just added very easy support for starting a `tmate` session in the image, see https://github.com/niteoweb/nix-docker-base#connecting-with-ssh-during-ci. For GitHub Actions, one can use
```
defaults:
  run:
    shell: bash-tmate {0}
```

To make it start a tmate session when any `run` step fails. Similarly for CircleCI:
```
executors:
  my-executor:
    docker:
      - image: niteo/nixpkgs-nixos-unstable:1dc37370c489b610f8b91d7fdd40633163ffbafd
    shell: bash-tmate -eo pipefail
```
